# Import necessary python libs +  Keras + Sklearn

In [36]:
import os
import tensorflow
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib as plt
import plotly.express as px


from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, InputLayer, Dropout
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping
from keras.regularizers import l1, l2

In [ ]:
import random

def plot_convergence(hist, metric): 
    df = pd.DataFrame(hist.history)
    fig = px.line(df,
                x=np.arange(df[metric].shape[0]),
                y=[f'{metric}', f'val_{metric}'])
    fig.show()

def reset_seeds():
    os.environ['PYTHONHASHSEED']=str(42)
    tf.random.set_seed(42)
    np.random.seed(42)
    random.seed(42)

# Reading Dataset

In [38]:
data = pd.read_csv('https://raw.githubusercontent.com/renansantosmendes/lectures-cdas-2023/master/fetal_health.csv')
data.head()

   baseline value  accelerations  ...  histogram_tendency  fetal_health
0           120.0          0.000  ...                 1.0           2.0
1           132.0          0.006  ...                 0.0           1.0
2           133.0          0.003  ...                 0.0           1.0
3           134.0          0.003  ...                 1.0           1.0
4           132.0          0.007  ...                 1.0           1.0

[5 rows x 22 columns]

# Clean up data and standardize dataset

In [39]:
## Remove class that we want to answer on this execise
x = data.drop(["fetal_health"], axis = 1)
y = data["fetal_health"] - 1

columns_names = list(x.columns)
x_df = preprocessing.StandardScaler().fit_transform(x) 
x_df = pd.DataFrame(x_df, columns=columns_names)

#devide dataset for training / test
x_train, X_test, y_train, Y_test = train_test_split(x_df, y, test_size=0.3, random_state=42)

#Keras understand that first class is 0
y_train = keras.utils.to_categorical(y_train)
Y_test = keras.utils.to_categorical(Y_test)

In [40]:
x_train.head()

      baseline value  accelerations  ...  histogram_variance  histogram_tendency
1718       -0.234167       1.247640  ...            0.110177            1.112980
857         0.883886      -0.822388  ...           -0.580173           -0.524526
1075        0.375680      -0.304881  ...            0.144694            1.112980
371         0.477322      -0.822388  ...           -0.476621            1.112980
222        -0.437449      -0.304881  ...           -0.511138            1.112980

[5 rows x 21 columns]

#Creating Model and Adding the Layears

In [41]:
reset_seeds()
data_shape = x_train.iloc[0].shape

# WHAT is Sequential
# Sequential is the simplest way to build a neural network in Keras. Uses when no complex connections. Other types are Functional API and SubClassing

model = Sequential()

# Addign input layer
model.add(InputLayer(shape=data_shape))

# WHAT IS DENSE?
# Dense is a layer that is a fully connect Neural Network Layer
# Performs linear combination + activation
#Adding 4 Hidden Layers with 30 Neurons
model.add(Dense(units=30, activation='relu'))
model.add(Dense(units=30, activation='relu'))
model.add(Dense(units=30, activation='relu'))
model.add(Dense(units=30, activation='relu'))

#Adding Output Layer
#Softmax converts the outputs into probability
model.add(Dense(units=3, activation='softmax'))

In [42]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_14 (Dense)                │ (None, 30)             │           660 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 30)             │           930 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 30)             │           930 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 30)             │           930 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 3)              │            93 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,543 (13.84 KB)

 Trainable params: 3,543 (13.84 KB)

 Non-trainable params: 0 (0.00 B)

In [43]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [44]:
%%time
hist = model.fit(x = x_train, y = y_train, epochs = 30, batch_size = 128, validation_split = 0.2)

Epoch 1/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 47ms/step - accuracy: 0.5261 - loss: 1.0427 - val_accuracy: 0.7819 - val_loss: 0.9003
Epoch 2/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7681 - loss: 0.8523 - val_accuracy: 0.8054 - val_loss: 0.7581
Epoch 3/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7723 - loss: 0.7340 - val_accuracy: 0.8054 - val_loss: 0.6676
Epoch 4/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7731 - loss: 0.6480 - val_accuracy: 0.8255 - val_loss: 0.5925
Epoch 5/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8042 - loss: 0.5743 - val_accuracy: 0.8356 - val_loss: 0.5272
Epoch 6/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8244 - loss: 0.5140 - val_accuracy: 0.8423 - val_loss: 0.4743
Epoch 7/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8269 - loss: 0.4680 - val_accuracy: 0.8423 - val_loss: 0.4331
Epoch 8/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8303 - loss: 0.4323 - val_accuracy: 0.8356 - val_loss: 0.3985
Epoch 9/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8353 - loss: 0.3995 - val_accuracy: 0.8523 - val_loss: 0.3637
Epoch 10/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8605 - loss: 0.3680 - val_accuracy: 0.8792 - val_loss: 0.3329
Epoch 11/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8756 - loss: 0.3389 - val_accuracy: 0.8859 - val_loss: 0.3075
Epoch 12/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8840 - loss: 0.3151 - val_accuracy: 0.8893 - val_loss: 0.2883
Epoch 13/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8941 - loss: 0.2961 - val_accuracy: 0.8893 - val_loss: 0.2746
Epoch 14/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8992 - loss: 0.2802 - val_accuracy: 0.8960 - val_loss: 0.2652
Epoch 15/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9000 - loss: 0.2665 - val_accuracy: 0.8993 - val_loss: 0.2578
Epoch 16/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9059 - loss: 0.2538 - val_accuracy: 0.8960 - val_loss: 0.2517
Epoch 17/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9092 - loss: 0.2428 - val_accuracy: 0.8960 - val_loss: 0.2467
Epoch 18/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9126 - loss: 0.2329 - val_accuracy: 0.9027 - val_loss: 0.2419
Epoch 19/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9143 - loss: 0.2237 - val_accuracy: 0.9027 - val_loss: 0.2369
Epoch 20/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9151 - loss: 0.2153 - val_accuracy: 0.8926 - val_loss: 0.2324
Epoch 21/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9160 - loss: 0.2078 - val_accuracy: 0.8960 - val_loss: 0.2284
Epoch 22/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9202 - loss: 0.2005 - val_accuracy: 0.8926 - val_loss: 0.2246
Epoch 23/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9277 - loss: 0.1939 - val_accuracy: 0.8960 - val_loss: 0.2207
Epoch 24/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9286 - loss: 0.1879 - val_accuracy: 0.9027 - val_loss: 0.2174
Epoch 25/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9294 - loss: 0.1820 - val_accuracy: 0.9027 - val_loss: 0.2139
Epoch 26/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9303 - loss: 0.1768 - val_accuracy: 0.9060 - val_loss: 0.2103
Epoch 27/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9328 - loss: 0.1714 - val_accuracy: 0.9094 - val_loss: 0.2071
Epoch 28/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9353 - loss: 0.1666 - val_accuracy: 0.9094 - val_loss: 0.2051
Epoch 29/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9387 - loss: 0.1623 - val_accuracy: 0.9094 - val_loss: 0.2030
Epoch 30/30
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9387 - loss: 0.1582 - val_accuracy: 0.9128 - val_loss: 0.2003
CPU times: user 6.06 s, sys: 354 ms, total: 6.41 s
Wall time: 6.3 s

# Evaluating the Model

In [45]:
plot_convergence(hist, 'loss')